import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {handleFarmerMessage} from '../public/account.js';import {poolLots} from '../public/core.js';
const model=JSON.parse(await readFile(new URL('../public/model.json',import.meta.url),'utf8'));
const general={profile:{id:'general'},order:null,lots:[],choices:[],offline:true};
function onboard(){let session={draft:{}};for(const text of ['INICIAR','ACEITO','Ana','Boa Vista','PT','CONFIRMO'])session=handleFarmerMessage(text,session,model,general).session;return session;}
test('onboarding asks one question at a time, records consent, and confirms account explicitly',()=>{let r=handleFarmerMessage('OI',{draft:{}},model,general);assert.match(r.reply,/ACEITO/);assert.equal(r.session.account,undefined);r=handleFarmerMessage('não',r.session,model,general);assert.equal(r.session.onboarding.step,'consent');for(const text of ['ACEITO','Ana','Boa Vista','EN'])r=handleFarmerMessage(text,r.session,model,general);assert.equal(r.session.account,undefined);assert.equal(r.session.onboarding.step,'review');r=handleFarmerMessage('CONFIRMO',r.session,model,general);assert.equal(r.session.account.name,'Ana');assert.equal(r.session.account.location,'Boa Vista');assert.equal(r.session.account.language,'en');assert.ok(r.session.account.consent.acceptedAt);const again=handleFarmerMessage('INICIAR',r.session,model,general);assert.equal(again.session.account.id,r.session.account.id);});
test('a first harvest is retained through onboarding and profile fields seed later harvests',()=>{let r=handleFarmerMessage('tenho 80 kg de mandioca',{draft:{}},model,general);for(const text of ['ACEITO','Ana','Boa Vista','PT','CONFIRMO'])r=handleFarmerMessage(text,r.session,model,general);assert.equal(r.session.draft.quantityKg,80);assert.equal(r.session.draft.location,'Boa Vista');assert.match(r.reply,/classificação/);r=handleFarmerMessage('classe A, 2026-10-05, BRL 4/kg',r.session,model,general);assert.equal(r.lot,undefined);r=handleFarmerMessage('CONFIRMO',r.session,model,general);assert.equal(r.lot.farmerId,r.session.account.id);assert.equal(r.session.account.name,'Ana');assert.equal(r.lot.farmer,'Ana');});
test('account record queries isolate farmers and never merge by matching names',()=>{const session=onboard(),own={id:'my-lot',farmerId:session.account.id,farmer:'Ana',quantityKg:40,crop:'cassava',harvestDate:'2026-10-05',status:'available'},other={...own,id:'private-lot',farmerId:'another-person',farmer:'Other farmer'};const r=handleFarmerMessage('LOTES',session,model,{...general,lots:[own,other]});assert.match(r.reply,/my-lot/);assert.doesNotMatch(r.reply,/private-lot/);assert.match(handleFarmerMessage('RETIRAR LOTE private',session,model,{...general,lots:[own,other]}).reply,/não encontrado/);});
test('profile changes and withdrawal require confirmation; cancellation preserves records',()=>{let session=onboard();let r=handleFarmerMessage('ALTERAR LOCAL Bonfim',session,model,general);assert.equal(r.session.account.location,'Boa Vista');r=handleFarmerMessage('CONFIRMO',r.session,model,general);assert.equal(r.session.account.location,'Bonfim');const lot={id:'abcdef12-lot',farmerId:session.account.id,quantityKg:40,status:'available'};r=handleFarmerMessage('RETIRAR LOTE abcdef12',session,model,{...general,lots:[lot]});assert.equal(r.lotUpdate,undefined);assert.equal(handleFarmerMessage('CANCELAR',r.session,model,general).lotUpdate,undefined);r=handleFarmerMessage('CONFIRMO',r.session,model,{...general,lots:[lot]});assert.equal(r.lotUpdate.status,'withdrawn');assert.equal(r.lotUpdate.farmerId,session.account.id);const reserved=handleFarmerMessage('RETIRAR LOTE abcdef12',session,model,{...general,lots:[{...lot,reservedOrderId:'order'}]});assert.equal(reserved.session.pendingWithdrawal,undefined);assert.match(reserved.reply,/revisão/);});
test('offline status and support distinguish local records from delivery and human response',()=>{const session=onboard();assert.match(handleFarmerMessage('STATUS',session,model,general).reply,/comprador ainda não recebeu/);const r=handleFarmerMessage('SUPORTE',session,model,general);assert.equal(r.supportRequest.farmerId,session.account.id);assert.match(r.reply,/Nenhum atendente foi notificado/);const lot={id:'withdrawn',crop:'tomato',location:'Bonfim, Roraima',grade:'A',harvestDate:'2026-10-04',quantityKg:200,confirmedAt:'now',status:'withdrawn'};assert.equal(poolLots([lot]).quantityKg,0);});
