import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {handleMessage,poolLots,compare,validateLot,demoCosts} from '../public/core.js';
const model=JSON.parse(await readFile(new URL('../public/model.json',import.meta.url),'utf8'));
test('Portuguese intake asks missing fields and only explicit confirmation creates a lot',()=>{let r=handleMessage('Sou Ana, tenho 120 kg de tomate em Bonfim, classe A',{draft:{}},model);assert.match(r.reply,/data/);assert.equal(r.lot,undefined);r=handleMessage('2026-10-04, R$ 3,50/kg',r.session,model);assert.match(r.reply,/CONFIRMO/);assert.equal(r.lot,undefined);r=handleMessage('CONFIRMO',r.session,model);assert.equal(r.lot.quantityKg,120);assert.equal(r.lot.localPriceBrl,3.5);assert.ok(r.lot.confirmedAt);assert.deepEqual(r.session.draft,{});});
test('invalid calendar date and zero quantity rejected',()=>{const base={farmer:'Ana',crop:'tomato',location:'Bonfim, Roraima',quantityKg:120,grade:'A',harvestDate:'2026-10-04',localPriceBrl:3.5};assert.throws(()=>validateLot({...base,harvestDate:'2026-02-30'}));assert.throws(()=>validateLot({...base,quantityKg:0}));});
test('pool excludes wrong grade, date, unconfirmed and reserved lots and caps allocation',()=>{const l={id:'1',farmer:'Ana',crop:'tomato',location:'Bonfim, Roraima',grade:'A',harvestDate:'2026-10-04',quantityKg:120,localPriceBrl:3.5,confirmedAt:'now'};const pool=poolLots([l,{...l,id:'2',quantityKg:100},{...l,id:'3',grade:'B'},{...l,id:'4',harvestDate:'2026-10-07'},{...l,id:'5',confirmedAt:null},{...l,id:'6',reservedOrderId:'other'}]);assert.equal(pool.quantityKg,200);assert.deepEqual(pool.allocations.map(a=>a.kg),[120,80]);assert.equal(pool.matched,true);});
test('FX conversion, loss, deductions and allocation conserve net earnings',()=>{const l={id:'1',farmer:'Ana',crop:'tomato',location:'Bonfim, Roraima',grade:'A',harvestDate:'2026-10-04',quantityKg:200,localPriceBrl:3.5,confirmedAt:'now'};const c=compare(poolLots([l]));assert.equal(c.localNet,650);assert.equal(c.billedKg,190);assert.equal(c.grossGyd,47500);assert.equal(c.grossBrl,1187.5);assert.equal(c.totalCosts,303.75);assert.equal(c.crossNet,883.75);assert.equal(c.farmers[0].crossNet,c.crossNet);assert.throws(()=>compare(poolLots([l]),{...demoCosts,gydPerBrl:0}));});
test('unknown language abstains, cancellation clears draft, confirmation cannot fabricate missing fields',()=>{assert.equal(handleMessage('zyx qqq',{draft:{}},model).intent.intent,'unknown');assert.deepEqual(handleMessage('cancelar',{draft:{farmer:'Ana'}},model).session.draft,{});assert.equal(handleMessage('CONFIRMO',{draft:{}},model).lot,undefined);});

test('messaging earnings and choice require a second explicit farmer confirmation',()=>{
 const lots=[{id:'ana',farmer:'Ana',crop:'tomato',location:'Bonfim, Roraima',grade:'A',harvestDate:'2026-10-04',quantityKg:120,localPriceBrl:3.5,confirmedAt:'2026-10-04T00:00:00Z'},{id:'paulo',farmer:'Paulo',crop:'tomato',location:'Bonfim, Roraima',grade:'A',harvestDate:'2026-10-04',quantityKg:100,localPriceBrl:3.5,confirmedAt:'2026-10-04T00:01:00Z'}];
 const context={lots,choices:[],costs:demoCosts},session={draft:{},lastLotId:'ana',source:'twilio-inbound'};
 let r=handleMessage('comparar ganhos',session,model,context);assert.match(r.reply,/530.25/);assert.match(r.reply,/2026-10-03/);assert.doesNotMatch(r.reply,/Abra/);
 r=handleMessage('ESCOLHO PROPOSTA',session,model,context);assert.equal(r.choice,undefined);assert.match(r.reply,/Responda CONFIRMO/);
 r=handleMessage('CONFIRMO',r.session,model,context);assert.equal(r.choice.lotId,'ana');assert.equal(r.choice.quantityKg,120);assert.equal(r.choice.humanConfirmed,true);assert.equal(r.choice.confirmationSource,'twilio-inbound');assert.equal(r.choice.status,'awaiting buyer confirmation and trade-requirement checks');
 const repeated=handleMessage('ESCOLHO LOCAL',r.session,model,{...context,choices:[r.choice]});assert.equal(repeated.session.pendingChoice,null);assert.match(repeated.reply,/já tem uma escolha/);
 const incomplete=handleMessage('comparar ganhos',session,model,{...context,lots:[lots[0]]});assert.match(incomplete.reply,/80 kg/);assert.equal(incomplete.choice,undefined);
});

test('general intake requires crop and location and never invents a buyer order',()=>{const context={profile:{id:'general'},order:null,lots:[],choices:[]};let r=handleMessage('Sou Ana, tenho 120 kg, classe A',{draft:{}},model,context);assert.match(r.reply,/O que você colheu/);r=handleMessage('mandioca',r.session,model,context);assert.match(r.reply,/Onde está/);r=handleMessage('em Boa Vista, 2026-10-04, BRL 4/kg',r.session,model,context);assert.match(r.reply,/CONFIRMO/);r=handleMessage('CONFIRMO',r.session,model,context);assert.equal(r.lot.crop,'cassava');assert.equal(r.lot.location,'Boa Vista');assert.equal(r.lot.localPriceBrl,4);assert.match(handleMessage('comparar ganhos',r.session,model,{...context,lots:[r.lot]}).reply,/Ainda não há oferta/);});
test('demo pooling excludes harvests from a different location',()=>{const lot={id:'elsewhere',farmer:'Ana',crop:'tomato',location:'Boa Vista',grade:'A',harvestDate:'2026-10-04',quantityKg:200,localPriceBrl:4,confirmedAt:'now'};assert.equal(poolLots([lot]).quantityKg,0);});
