import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createPostgresStore} from './postgres.mjs';import {processInbound,companionOperation} from '../shared.mjs';
if(!process.env.DATABASE_URL)throw Error('DATABASE_URL is required for the real PostgreSQL integration tests.');
const a=await createPostgresStore(process.env.DATABASE_URL),b=await createPostgresStore(process.env.DATABASE_URL),model=JSON.parse(await readFile(new URL('../public/model.json',import.meta.url),'utf8'));let sid=0;const from='whatsapp:+postgres-integration-'+Date.now();const send=body=>a.transaction({from,body},db=>processInbound(db,{From:from,MessageSid:'SM-pg-'+(++sid),Body:body},model));
test('two worker connections share verified accounts, document workflows and durable delivery jobs',async()=>{for(const text of ['START','EN','I AGREE','Ana','Bonfim','CONFIRM'])await send(text);const pair=await a.transaction({action:'link/request'},db=>companionOperation(db,'link/request','POST',{label:'test',language:'en'},'','test',model));await send(pair.command);await send('CONFIRM');const input={id:pair.id,claim:pair.claim};const linked=await b.transaction({action:'link/claim',input},db=>companionOperation(db,'link/claim','POST',input,'','test',model));assert.equal(linked.state,'linked');await send('I have 120 kg of tomatoes, grade A, 2026-10-04, BRL 3.5/kg');await send('CONFIRM');await send('prepare a harvest summary');await send('CONFIRM');await send('email document to ana@example.com');await send('CONFIRM');const snapshot=await b.transaction({action:'snapshot',token:linked.token},db=>companionOperation(db,'snapshot','GET',{},linked.token,'test',model));assert.equal(snapshot.lots.length,1);assert.equal(snapshot.documents.length,1);assert.equal(snapshot.deliveryJobs.length,1);const job=(await a.pool.query('SELECT * FROM hl_email_jobs WHERE id=$1',[snapshot.deliveryJobs[0].id])).rows[0];assert.equal(job.destination,'ana@example.com');assert.equal(job.status,'queued');assert.match(job.body,/120 kg/);});
test('concurrent workers preserve 50 same-account updates and rollback failed writes',async()=>{const owner=from+'-load';await a.transaction({from:owner},db=>{db.accounts['load-owner']={id:'load-owner',counter:0,revision:0};});const start=performance.now();await Promise.all(Array.from({length:50},(_,i)=>(i%2?a:b).transaction({from:owner},db=>{db.accounts['load-owner'].counter++;})));const count=await b.transaction({from:owner},db=>db.accounts['load-owner'].counter);assert.equal(count,50);await assert.rejects(a.transaction({from:owner},db=>{db.accounts['load-owner'].counter=999;throw Error('rollback');}),/rollback/);assert.equal(await b.transaction({from:owner},db=>db.accounts['load-owner'].counter),50);console.log(JSON.stringify({test:'50 concurrent same-account updates across two pools',elapsedMs:Math.round(performance.now()-start),lostUpdates:0}));});
test('account records exceed demo document cap and remain isolated across independent accounts',async()=>{const owner=from+'-large';await a.transaction({from:owner},db=>{db.accounts['large-owner']={id:'large-owner',revision:0};db.lots=Array.from({length:300},(_,i)=>({id:owner+'-'+i,farmerId:'large-owner',quantityKg:20,crop:'tomato',location:'Bonfim',grade:'A',harvestDate:'2026-10-04',confirmedAt:'2026-10-04T00:00:00Z',status:'available'}));assert.ok(Buffer.byteLength(JSON.stringify(db.lots))>14500);});assert.equal(await b.transaction({from:owner},db=>db.lots.length),300);assert.equal(await b.transaction({from:from+'-isolated'},db=>db.lots.length),0);});
test.after(async()=>{await a.pool.end();await b.pool.end();});

test('provider retries remain idempotent after account history is pruned',async()=>{const owner=from+'-receipt',route={from:owner,body:'START',messageId:'SM-durable-'+Date.now()};const first=await a.transaction(route,db=>processInbound(db,{From:owner,Body:route.body,MessageSid:route.messageId},model));await a.transaction({from:owner},db=>{db.seen={};});const second=await b.transaction(route,()=>{throw Error('Duplicate must not reach the engine');});assert.equal(first,second);await assert.rejects(b.transaction({...route,body:'changed'},()=>null),e=>e.status===409);});
