import {readFile,writeFile,mkdir} from 'node:fs/promises';
const core=await readFile(new URL('../public/core.js',import.meta.url),'utf8'),model=await readFile(new URL('../public/model.json',import.meta.url),'utf8');
const accountCore=await readFile(new URL('../public/account.js',import.meta.url),'utf8');
const wrapper=`
exports.handler = async function(context,event,callback){
 const response=new Twilio.twiml.MessagingResponse();
 const client=context.getTwilioClient(),service=context.SYNC_SERVICE_SID;
 if(!service){response.message('Configuração pendente. O coordenador precisa conectar o armazenamento. Nenhum lote salvo.');return callback(null,response);}
 const documents=client.sync.v1.services(service).documents;
 const name='harvestlink-demo-v1';
 try{
  if(!event.MessageSid||!event.From||typeof event.Body!=='string')throw Error('Invalid message');
  for(let attempt=0;attempt<3;attempt++){
   let doc;try{doc=await documents(name).fetch();}catch(e){if(e.status!==404)throw e;try{doc=await documents.create({uniqueName:name,data:{sessions:{},lots:[],choices:[],seen:{},evidence:[]}});}catch(createError){if(createError.status===409)continue;throw createError;}}
   const data=JSON.parse(JSON.stringify(doc.data));
   if(data.seen[event.MessageSid]){response.message(data.seen[event.MessageSid]);return callback(null,response);}
   const profile=context.HARVESTLINK_PROFILE==='bonfim'?profiles.bonfim:profiles.general;
   const result=handleFarmerMessage(event.Body,data.sessions[event.From]||{draft:{},source:'twilio-inbound'},model,{lots:data.lots,choices:data.choices,costs:demoCosts,profile,order:profile.id==='bonfim'?demoOrder:null});
   data.sessions[event.From]=result.session;if(result.lotUpdate)data.lots=data.lots.map(l=>l.id===result.lotUpdate.id?{...l,...result.lotUpdate}:l);if(result.supportRequest)data.supportRequests=(data.supportRequests||[]).concat(result.supportRequest);if(result.lot)data.lots.push({...result.lot,providerSid:event.MessageSid});if(result.choice)data.choices.push(result.choice);
   data.seen[event.MessageSid]=result.reply;const sids=Object.keys(data.seen);for(const sid of sids.slice(0,-12))delete data.seen[sid];
   data.evidence=(data.evidence||[]).concat({sid:event.MessageSid,at:new Date().toISOString(),reply:result.reply}).slice(-6);
   if(Buffer.byteLength(JSON.stringify(data),'utf8')>14500){response.message('Armazenamento de teste cheio. Nada foi salvo. Peça ao coordenador para exportar os registros antes de continuar.');return callback(null,response);}
   try{await documents(name).update({data,ifMatch:doc.revision});response.message(result.reply);return callback(null,response);}catch(e){if(e.status===412||e.status===409)continue;throw e;}
  }
  throw Error('Concurrent update');
 }catch(error){console.error('HarvestLink storage error',error.status||'runtime');response.message('Não consegui salvar com segurança. Tente novamente. Nenhuma confirmação foi registrada nesta tentativa.');return callback(null,response);}
};
`;
await mkdir(new URL('../twilio/',import.meta.url),{recursive:true});
await writeFile(new URL('../twilio/harvestlink-reply.protected.js',import.meta.url),`// Generated by npm run build:twilio. Set visibility Protected. No credentials belong in this file.\nconst crypto=require('crypto');\nconst model=${model};\n${core.replaceAll('export ','')}\n${accountCore.replace(/^import .*;\r?\n/,'').replaceAll('export ','')}\n${wrapper}`);
console.log('Generated protected Twilio Function with shared model and dialogue engine.');
